### ISSUE TITLE
add documentation to explain how to build and start the system

### ISSUE THREAD

**Issue by mox601** [Dani7B/RTwUP#12]
e.g. I'd like something like this: 
1. build with mvn clean package
2. start redis with the command `...` (using port X, etc... )
3. start the socket.io server with command `...`
4. launch the executable with java -jar <jarname>.jar <lat-long query params or file containing them>
5. you can see the output of the system at [this page](http://localhost/rtwup)

**Comment by Dani7B** [comment]
Documentation added in wiki and linked in README
