### ISSUE TITLE
reconfigure spout to be able to filter tweets based on different queries

### ISSUE THREAD

**Issue by mox601** [Dani7B/RTwUP#25]
required queries should include following parameters from 
[Twitter API](https://dev.twitter.com/docs/api/1.1/post/statuses/filter): 
- track
- locations

Useful documentation passage about OR combination of different query parameters: 

> The track, follow, and locations fields should be considered to be combined with an OR operator. track=foo&follow=1234 _returns Tweets matching "foo" OR created by user 1234_. 

This determines that, if needed, AND query semantics should be dealt with inside the Topology.

**Comment by Dani7B** [comment]
Now the Spout filters the stream taking into account location and keywords (in OR).
